### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by stewartoallen** [bluelightning32/walnut-javascript#1]
on a clean checkout

 ```
git submodule update --recursive --remote
```

doesn't do anything. are there other missing dependencies?

**Comment by hrgdavor** [comment]
the setup proces is sth I wrote quiclky on my first build, but is incomplete... I did it on windows, and also had to install cmake, nijnja, and whatnot, I do not remember any more :(

**Comment by bluelightning32** [comment]
It should have been
```
git submodule update --recursive --init
```

I updated the README.md.
